[port_aliases]
UB = ["btnU"]
DB = ["btnD"]
LB = ["btnL"]
RB = ["btnR"]
CB = ["btnC"]
dp = ["DP"]
switches = ["sw"]
lights = ["LED"]
anode = ["an"]
segment = ["seg"]

[boards.classic]
path = "board__classic.py"
inputs = { clk = 1, UB = 1, DB = 1, LB = 1, RB = 1, CB = 1, switches = 16 }
outputs = { segment = 7, dp = 1, anode = 4, lights = 16 }

[boards.dotmatrix]
path = "board__dotmatrix.py"
inputs = { clk = 1, UB = 1, DB = 1, LB = 1, RB = 1, CB = 1, switches = 16 }
outputs = { select = 4, matrix = 21, lights = 16 }

[boards.calculator]
path = "board__calculator.py"
inputs = { clk = 1, b0 = 1, b1 = 1, b2 = 1, b3 = 1, b4 = 1, b5 = 1, b6 = 1, b7 = 1, b8 = 1, b9 = 1, equals = 1, clear = 1, divide = 1, multiply = 1, subtract = 1, add = 1 }
outputs = { select = 4, matrix = 15 }

[boards.switches]
path = "board__switches.py"
inputs = { switches = 16 }
outputs = { lights = 16 }

[boards.apple_game]
path = "board__apple_game.py"
inputs = { clk = 1, left = 1, right = 1, restart = 1 }
outputs = { apple_spawn_row = 2, apple_left_col = 3, apple_center_col = 3, apple_right_col = 3, basket = 3, oof = 3, score_select = 2, score_pattern = 15, high_select = 2, high_pattern = 15 }
